// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/cn/cat/netty/demo/protoc/protoc/MsgInfo.proto

package cn.cat.netty.demo.protoc.domain;

public interface MsgBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.cat.netty.demo.protoc.domain.MsgBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string channelId = 1;</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <code>string channelId = 1;</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <code>string msgInfo = 2;</code>
   * @return The msgInfo.
   */
  java.lang.String getMsgInfo();
  /**
   * <code>string msgInfo = 2;</code>
   * @return The bytes for msgInfo.
   */
  com.google.protobuf.ByteString
      getMsgInfoBytes();
}
